on:
  push:
    branches:
      - deploy
      
name: build gatsby
jobs:
  build_gatsby:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: npm install
        run: npm install

      - name: npm run build
        env:
          GH_API_KEY: ${{ secrets.TOKEN }}
        run: npm run build

      - name: deploy
        uses: maxheld83/ghpages@v0.2.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_PAT: ${{ secrets.TOKEN }}
          BUILD_DIR: 'public/'
